# Generated by Django 4.2.6 on 2023-10-17 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geographyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countrys'},
        ),
    ]
